GET https://io.adafruit.com/api/v2/${process.env.USER_NAME_ADAFRUIT}/feeds/sync/data/last
X-AIO-Key: `${process.env.KEY_ADAFRUIT}`

###
POST https://io.adafruit.com/api/v2/${process.env.USER_NAME_ADAFRUIT}/feeds/sync/data
X-AIO-Key: `${process.env.KEY_ADAFRUIT}`
Content-Type: application/json

{
    "datum" : { "value" : "1" }
}

###
PUT https://io.adafruit.com/api/v2/${process.env.USER_NAME_ADAFRUIT}/feeds/sync/data/0F17Z6X3EZE3TKB5EH0CEM3KTV
X-AIO-Key: `${process.env.KEY_ADAFRUIT}`
Content-Type: application/json

{
    "datum" : { "value" : "1" }
}

###
PUT https://io.adafruit.com/api/v2/${process.env.USER_NAME_ADAFRUIT}/feeds/pump/data/0F18WS8B5YE3NRPZ62K6KH18SH
X-AIO-Key: `${process.env.KEY_ADAFRUIT}`
Content-Type: application/json

{
    "datum" : { "value" : "0" }
}

###
POST https://io.adafruit.com/api/v2/${process.env.USER_NAME_ADAFRUIT}/feeds/pump/data
X-AIO-Key: `${process.env.KEY_ADAFRUIT}`
Content-Type: application/json

{
    "datum" : { "value" : "1" }
}

###
GET https://io.adafruit.com/api/v2/${process.env.USER_NAME_ADAFRUIT}/feeds/pump/data/last
X-AIO-Key: `${process.env.KEY_ADAFRUIT}`

