POST http://localhost:5000/data
Content-Type: application/json

{
    "id" : 2,
    "category": "Light",
    "value" : 15,
    "id_garden" : 1,
    "time" : "2001-08-20"
}

###
GET http://localhost:5000/data/search?idGarden=1&startDay=2000-01-01&endDay=2010-03-05

###
GET http://localhost:5000/garden
